### ISSUE TITLE
Admin Views to Create-Edit-Delete Events and Manage Available Tickets

### ISSUE THREAD

**Issue by vani4ka66** [vani4ka66/SoftUni-JS-TeamWork-Ticket-Store#2]

**Comment by vani4ka66** [comment]
•	Administration interface for addition, editing and deletion of events

**Comment by andreybozhkov** [comment]
![admin view - edit event](https://user-images.githubusercontent.com/19271242/27933840-b01d9c3a-62ab-11e7-960e-3941ec6420d4.png)
![admin view - events dashboard](https://user-images.githubusercontent.com/19271242/27933839-b01ad784-62ab-11e7-859c-dbd4da3a0408.png)
![admin view - manage available tickets](https://user-images.githubusercontent.com/19271242/27933837-b019cfba-62ab-11e7-8b33-9c7fc7bdc73c.png)
![admin view - add new event](https://user-images.githubusercontent.com/19271242/27933838-b01ac532-62ab-11e7-9cae-e1a9dc1c30d1.png)
